Add divide by zero check (#191)
On several servers (Ubuntu 18.04) DEMAND_DATA_TOTAL is 0 currently and is causing an error

Traceback (most recent call last):
  File "/usr/local/bin/zfs-linux", line 178, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/zfs-linux", line 76, in main
    DATA_DEMAND_PERCENT = DEMAND_DATA_HITS / DEMAND_DATA_TOTAL * 100
ZeroDivisionError: division by zero